spring:
  redis:
    redisson:
      # 配置单点模式
      config: classpath:config/redisson-single-dev.yml
    open: true  # 是否开启redis缓存  true开启   false关闭
    host: 127.0.0.1
    port: 6379
    database: 12
    password:         # 密码（默认为空）
    timeout: 10s  # 连接超时时长（毫秒）
    lettuce:
      pool:
        min-idle: 0  # 连接池中的最小空闲连接
        max-idle: 8  # 连接池中的最大空闲连接
        max-active: 8 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms  # 连接池最大连接数（使用负值表示没有限制）
