spring:
  application:
    name: zuul-server
server:
  port: 3003
eureka:   #注册中心配置
  instance:
    prefer-ip-address: true #以IP形式注册
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 90  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    service-url:
      defaultZone: http://user:123456@127.0.0.1:11111/eureka/
zuul:
  ignoredServices: '*' #配置的路由，其他的使用默认路由
  routes:
    gateway-client: /client/**  #服务名: /client/** 将gateway-client服务映射到client路径


