server:
  port: 8084
spring:
  application:
    name: gateway-server
    # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: gateway-client
        uri: lb://gateway-client
        predicates:
        - Path=/client/**
        filters:
        - StripPrefix=1
      - id: baidu
        uri:  https://www.baidu.com
        predicates:
        - Path=/baidu/**
        filters:
        - StripPrefix=1

eureka:   #组册中心配置
  instance:
    prefer-ip-address: true #以IP形式注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 90  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    service-url:
      defaultZone: http://user:123456@127.0.0.1:11111/eureka/