server:
  port: 5555
spring:
  application:
    name: gateway-server
    # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          # 自动路由 模式 大写的服务名路由
          enabled: false
          # 小写 服务名 默认大写
          lowerCaseServiceId: true
      routes:
      - id: gateway-client
        uri: lb://gateway-client
        predicates:
        - Path=/client/**
        filters:
        - StripPrefix=1
      - id: baidu
        uri:  https://www.baidu.com
        predicates:
        - Path=/baidu/**
        filters:
        - StripPrefix=1
      #spring.cloud.gateway.discovery.enabled= false,websocket可以，网关的本服务http服务路由失败;
      #但是如果配置改为spring.cloud.gateway.discovery.enabled= true,websocket不可以，报跨域的错误
      #所以暂时为拥有soket服务的 配置一个http路由   一个soket路由
      # stomp soket 配置
      - id: gateway-stomp-soket
        uri: lb://gateway-stomp
        predicates:
        - Path=/stomp/info/**
      - id: gateway-stomp-soket
        uri: lb:ws://gateway-stomp
        predicates:
        - Path=/stomp/**
      # stomp http 配置
      - id: gateway-stomp-api
        uri: lb://gateway-stomp
        predicates:
        - Path=/apistomp/**
        filters:
        - StripPrefix=1

eureka:   #注册中心配置
  instance:
    prefer-ip-address: true #以IP形式注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 90  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    service-url:
      defaultZone: http://user:123456@127.0.0.1:11111/eureka/